builds:
  -
    id: app1
    main: ./cmd/app1
    binary: app1
    targets:
      - darwin_arm64
      - linux_amd64
      - windows_amd64
  -
    id: app2
    main: ./cmd/app2
    binary: app2
    targets:
      - windows_amd64

archives:
  -
    id: app1
    builds:
      - app1
    format_overrides:
      -
        goos: windows
        format: zip
  -
    id: app2
    builds:
      - app2
    format_overrides:
      -
        goos: windows
        format: zip
