builds:
  -
    id: app1
    main: ./cmd/app1
    binary: app1
    targets:
      - darwin_arm64
      - linux_amd64
      - windows_amd64

archives:
  -
    format_overrides:
      -
        goos: windows
        format: zip
