builds:
  -
    main: ./cmd/app1
    binary: app1
    targets:
      - darwin_arm64
      - linux_amd64
      - windows_amd64

  -
    main: ./cmd/app2
    binary: app2
    targets:
      - windows_amd64
