builds:
  -
    id: app1
    main: ./cmd/app1
    binary: app1
    ldflags:
      - -s -w -X main.version=v{{ .Version }}
    targets:
      - darwin_arm64
      - linux_amd64
      - windows_amd64
  -
    id: app2
    main: ./cmd/app2
    binary: app2
    ldflags:
      - -s -w -X main.version=v{{ .Version }}
    targets:
      - windows_amd64

archives:
  -
    id: app1
    builds:
      - app1
    name_template: "app1_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      -
        goos: windows
        format: zip
  -
    id: app2
    builds:
      - app2
    name_template: "app2_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      -
        goos: windows
        format: zip

release:
  draft: true

changelog:
  use: github-native
