name: Release

on:
  create:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -
      name: checkout
      uses: actions/checkout@v2
      with:
        # goreleaserでコミットログを作成するために必要
        fetch-depth: 0
    -
      name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.7
    -
      name: Run Test
      run: |
        go test --race ./...
    -
      name: Generate Licenses
      run: |
        go install github.com/google/go-licenses@latest
        go-licenses save ./... --force --save_path="./licenses"
    -
      name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
